language: scala

jdk:
  - oraclejdk8
  - openjdk11

scala:
  - 2.12.8
  - 2.13.0-M5

env:
  global:
    - CI_HOME=`pwd`

script:
  - cd $CI_HOME/play-zipkin-tracing && sbt ++$TRAVIS_SCALA_VERSION test
